import type { Server } from '@/shared/types';

export const SERVERS: Server[] = [
  { id: 0, name: 'Vice City' },
  { id: 1, name: 'Phoenix' },
  { id: 2, name: 'Tucson' },
  { id: 3, name: 'Scottsdale' },
  { id: 4, name: 'Chandler' },
  { id: 5, name: 'Brainburg' },
  { id: 6, name: 'Saint Rose' },
  { id: 7, name: 'Mesa' },
  { id: 8, name: 'Red Rock' },
  { id: 9, name: 'Yuma' },
  { id: 10, name: 'Surprise' },
  { id: 11, name: 'Prescott' },
  { id: 12, name: 'Glendale' },
  { id: 13, name: 'Kingman' },
  { id: 14, name: 'Winslow' },
  { id: 15, name: 'Payson' },
  { id: 16, name: 'Gilbert' },
  { id: 17, name: 'Show Low' },
  { id: 18, name: 'Casa Grande' },
  { id: 19, name: 'Page' },
  { id: 20, name: 'Sun City' },
  { id: 21, name: 'Queen Creek' },
  { id: 22, name: 'Sedona' },
  { id: 23, name: 'Holiday' },
  { id: 24, name: 'Wednesday' },
  { id: 25, name: 'Yava' },
  { id: 26, name: 'Faraway' },
  { id: 27, name: 'Bumble Bee' },
  { id: 28, name: 'Christmas' },
  { id: 29, name: 'Mirage' },
  { id: 30, name: 'Love' },
  { id: 31, name: 'Drake' },
  { id: 32, name: 'Space' },
];
